---
language: node_js
node_js:
- 0.6
- 0.8
env:
  global:
  - secure: ! 'GZFMU6FhzZnGsuKz5wKjCOjJRjloozbMfKuMAmL3ai9aPRaDW4bO7MBCO4E6

      IC9Da/f7SZVVUbBA80izHpVpXSARonYec0i2IEHhC79lokly4EEMRr7W3bxP

      4ookfqZjXqIOG6+/YDbHtpXL5iAAP7HC1BHxE1hAogUhjVQg6MQ='
